/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mobile_robot_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[7] = {4, 2, 0, 1, 2, 2, 3};
static const casadi_int casadi_s1[9] = {2, 4, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s2[11] = {4, 2, 0, 3, 6, 0, 1, 2, 0, 1, 3};
static const casadi_int casadi_s3[9] = {4, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s6[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s9[15] = {4, 4, 0, 2, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};

/* mobile_robot_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[2x3])->(o0[4],o1[4x4,8nz],o2[4x2,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+9, *w6=w+25, *w7=w+29, *w8=w+33, *w9=w+37, w10, w11, w12, w13, w14, *w15=w+46, *w18=w+48, *w19=w+50, *w20=w+52, *w21=w+58, *w22=w+66;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @4 = input[3][0] */
  w4 = arg[3] ? arg[3][0] : 0;
  /* #9: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #10: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #11: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #12: @5 = input[1][0] */
  casadi_copy(arg[1], 16, w5);
  /* #13: {@6, @7, @8, @9} = horzsplit(@5) */
  casadi_copy(w5, 4, w6);
  casadi_copy(w5+4, 4, w7);
  casadi_copy(w5+8, 4, w8);
  casadi_copy(w5+12, 4, w9);
  /* #14: {NULL, NULL, @4, @10} = vertsplit(@6) */
  w4 = w6[2];
  w10 = w6[3];
  /* #15: @11 = (@2*@4) */
  w11  = (w2*w4);
  /* #16: @12 = sin(@1) */
  w12 = sin( w1 );
  /* #17: @13 = (@12*@10) */
  w13  = (w12*w10);
  /* #18: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #19: @11 = (@11-@13) */
  w11 -= w13;
  /* #20: output[1][0] = @11 */
  if (res[1]) res[1][0] = w11;
  /* #21: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #22: @11 = cos(@1) */
  w11 = cos( w1 );
  /* #23: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #24: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #25: @4 = (@4+@10) */
  w4 += w10;
  /* #26: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #27: {NULL, NULL, @4, @10} = vertsplit(@7) */
  w4 = w7[2];
  w10 = w7[3];
  /* #28: @13 = (@2*@4) */
  w13  = (w2*w4);
  /* #29: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #30: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #31: @13 = (@13-@14) */
  w13 -= w14;
  /* #32: output[1][2] = @13 */
  if (res[1]) res[1][2] = w13;
  /* #33: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #34: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #35: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #36: @4 = (@4+@10) */
  w4 += w10;
  /* #37: output[1][3] = @4 */
  if (res[1]) res[1][3] = w4;
  /* #38: {NULL, NULL, @4, @10} = vertsplit(@8) */
  w4 = w8[2];
  w10 = w8[3];
  /* #39: @13 = (@2*@4) */
  w13  = (w2*w4);
  /* #40: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #41: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #42: @13 = (@13-@14) */
  w13 -= w14;
  /* #43: output[1][4] = @13 */
  if (res[1]) res[1][4] = w13;
  /* #44: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #45: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #46: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #47: @4 = (@4+@10) */
  w4 += w10;
  /* #48: output[1][5] = @4 */
  if (res[1]) res[1][5] = w4;
  /* #49: {NULL, NULL, @4, @10} = vertsplit(@9) */
  w4 = w9[2];
  w10 = w9[3];
  /* #50: @13 = (@2*@4) */
  w13  = (w2*w4);
  /* #51: @12 = (@12*@10) */
  w12 *= w10;
  /* #52: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #53: @13 = (@13-@12) */
  w13 -= w12;
  /* #54: output[1][6] = @13 */
  if (res[1]) res[1][6] = w13;
  /* #55: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #56: @11 = (@11*@10) */
  w11 *= w10;
  /* #57: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #58: @4 = (@4+@11) */
  w4 += w11;
  /* #59: output[1][7] = @4 */
  if (res[1]) res[1][7] = w4;
  /* #60: @15 = zeros(2x4,2nz) */
  casadi_clear(w15, 2);
  /* #61: @16 = 00 */
  /* #62: @17 = 00 */
  /* #63: @18 = ones(2x1) */
  casadi_fill(w18, 2, 1.);
  /* #64: {@4, @11} = vertsplit(@18) */
  w4 = w18[0];
  w11 = w18[1];
  /* #65: @18 = vertcat(@16, @17, @4, @11) */
  rr=w18;
  *rr++ = w4;
  *rr++ = w11;
  /* #66: @19 = @18[:2] */
  for (rr=w19, ss=w18+0; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #67: (@15[:2] = @19) */
  for (rr=w15+0, ss=w19; rr!=w15+2; rr+=1) *rr = *ss++;
  /* #68: @19 = @15' */
  casadi_trans(w15,casadi_s1, w19, casadi_s0, iw);
  /* #69: @20 = project(@19) */
  casadi_project(w19, casadi_s0, w20, casadi_s2, w);
  /* #70: @21 = input[2][0] */
  casadi_copy(arg[2], 8, w21);
  /* #71: {@9, @8} = horzsplit(@21) */
  casadi_copy(w21, 4, w9);
  casadi_copy(w21+4, 4, w8);
  /* #72: {NULL, NULL, @4, @11} = vertsplit(@9) */
  w4 = w9[2];
  w11 = w9[3];
  /* #73: @10 = (@2*@4) */
  w10  = (w2*w4);
  /* #74: @13 = sin(@1) */
  w13 = sin( w1 );
  /* #75: @12 = (@13*@11) */
  w12  = (w13*w11);
  /* #76: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #77: @10 = (@10-@12) */
  w10 -= w12;
  /* #78: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #79: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #80: @11 = (@1*@11) */
  w11  = (w1*w11);
  /* #81: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #82: @4 = (@4+@11) */
  w4 += w11;
  /* #83: @16 = 00 */
  /* #84: @17 = 00 */
  /* #85: @19 = vertcat(@10, @4, @16, @17) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w4;
  /* #86: {NULL, NULL, @10, @4} = vertsplit(@8) */
  w10 = w8[2];
  w4 = w8[3];
  /* #87: @2 = (@2*@10) */
  w2 *= w10;
  /* #88: @13 = (@13*@4) */
  w13 *= w4;
  /* #89: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #90: @2 = (@2-@13) */
  w2 -= w13;
  /* #91: @3 = (@3*@10) */
  w3 *= w10;
  /* #92: @1 = (@1*@4) */
  w1 *= w4;
  /* #93: @0 = (@0*@1) */
  w0 *= w1;
  /* #94: @3 = (@3+@0) */
  w3 += w0;
  /* #95: @16 = 00 */
  /* #96: @17 = 00 */
  /* #97: @15 = vertcat(@2, @3, @16, @17) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  /* #98: @8 = horzcat(@19, @15) */
  rr=w8;
  for (i=0, cs=w19; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<2; ++i) *rr++ = *cs++;
  /* #99: @22 = project(@8) */
  casadi_project(w8, casadi_s3, w22, casadi_s2, w);
  /* #100: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<6; ++i) (*rr++) += (*cs++);
  /* #101: output[2][0] = @20 */
  casadi_copy(w20, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mobile_robot_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mobile_robot_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mobile_robot_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mobile_robot_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 72;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
