/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mobile_robot_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s4[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

/* mobile_robot_cost_y_0_fun:(i0[4],i1[2],i2[],i3[],i4[2x3])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3, w4, *w5=w+5, w6, w7, w8, w9;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #4: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #6: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #8: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #9: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #10: @2 = input[1][1] */
  w2 = arg[1] ? arg[1][1] : 0;
  /* #11: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #12: @2 = 1.5708 */
  w2 = 1.5707963267948966e+00;
  /* #13: @3 = 25 */
  w3 = 25.;
  /* #14: @4 = 25 */
  w4 = 25.;
  /* #15: @5 = input[4][0] */
  casadi_copy(arg[4], 6, w5);
  /* #16: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #17: @6 = (@0-@6) */
  w6  = (w0-w6);
  /* #18: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #19: @7 = 0.16 */
  w7 = 1.6000000000000003e-01;
  /* #20: @6 = (@6/@7) */
  w6 /= w7;
  /* #21: @7 = @5[1] */
  for (rr=(&w7), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #22: @7 = (@1-@7) */
  w7  = (w1-w7);
  /* #23: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #24: @8 = 0.16 */
  w8 = 1.6000000000000003e-01;
  /* #25: @7 = (@7/@8) */
  w7 /= w8;
  /* #26: @6 = (@6+@7) */
  w6 += w7;
  /* #27: @4 = (@4*@6) */
  w4 *= w6;
  /* #28: @3 = (@3-@4) */
  w3 -= w4;
  /* #29: @3 = atan(@3) */
  w3 = atan( w3 );
  /* #30: @2 = (@2+@3) */
  w2 += w3;
  /* #31: @3 = 1.5708 */
  w3 = 1.5707963267948966e+00;
  /* #32: @4 = 25 */
  w4 = 25.;
  /* #33: @6 = 25 */
  w6 = 25.;
  /* #34: @7 = @5[2] */
  for (rr=(&w7), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #35: @7 = (@0-@7) */
  w7  = (w0-w7);
  /* #36: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #37: @8 = 0.16 */
  w8 = 1.6000000000000003e-01;
  /* #38: @7 = (@7/@8) */
  w7 /= w8;
  /* #39: @8 = @5[3] */
  for (rr=(&w8), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #40: @8 = (@1-@8) */
  w8  = (w1-w8);
  /* #41: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #42: @9 = 0.16 */
  w9 = 1.6000000000000003e-01;
  /* #43: @8 = (@8/@9) */
  w8 /= w9;
  /* #44: @7 = (@7+@8) */
  w7 += w8;
  /* #45: @6 = (@6*@7) */
  w6 *= w7;
  /* #46: @4 = (@4-@6) */
  w4 -= w6;
  /* #47: @4 = atan(@4) */
  w4 = atan( w4 );
  /* #48: @3 = (@3+@4) */
  w3 += w4;
  /* #49: @2 = (@2+@3) */
  w2 += w3;
  /* #50: @3 = 1.5708 */
  w3 = 1.5707963267948966e+00;
  /* #51: @4 = 25 */
  w4 = 25.;
  /* #52: @6 = 25 */
  w6 = 25.;
  /* #53: @7 = @5[4] */
  for (rr=(&w7), ss=w5+4; ss!=w5+5; ss+=1) *rr++ = *ss;
  /* #54: @0 = (@0-@7) */
  w0 -= w7;
  /* #55: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #56: @7 = 0.16 */
  w7 = 1.6000000000000003e-01;
  /* #57: @0 = (@0/@7) */
  w0 /= w7;
  /* #58: @7 = @5[5] */
  for (rr=(&w7), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #59: @1 = (@1-@7) */
  w1 -= w7;
  /* #60: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #61: @7 = 0.16 */
  w7 = 1.6000000000000003e-01;
  /* #62: @1 = (@1/@7) */
  w1 /= w7;
  /* #63: @0 = (@0+@1) */
  w0 += w1;
  /* #64: @6 = (@6*@0) */
  w6 *= w0;
  /* #65: @4 = (@4-@6) */
  w4 -= w6;
  /* #66: @4 = atan(@4) */
  w4 = atan( w4 );
  /* #67: @3 = (@3+@4) */
  w3 += w4;
  /* #68: @2 = (@2+@3) */
  w2 += w3;
  /* #69: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mobile_robot_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
