/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mobile_robot_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[6] = {0, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s5[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s6[18] = {6, 7, 0, 1, 2, 3, 4, 5, 6, 8, 2, 3, 4, 5, 0, 1, 2, 3};
static const casadi_int casadi_s7[3] = {7, 0, 0};

/* mobile_robot_cost_y_0_fun_jac_ut_xt:(i0[4],i1[2],i2[],i3[],i4[2x3])->(o0[7],o1[6x7,8nz],o2[7x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  const casadi_int *cii;
  casadi_real w0, w1, w2, w3, w4, *w5=w+5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+23, *w19=w+31, w21, *w22=w+37, *w27=w+43, *w28=w+45;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #4: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #6: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #8: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #9: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #10: @2 = input[1][1] */
  w2 = arg[1] ? arg[1][1] : 0;
  /* #11: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #12: @2 = 1.5708 */
  w2 = 1.5707963267948966e+00;
  /* #13: @3 = 25 */
  w3 = 25.;
  /* #14: @4 = 25 */
  w4 = 25.;
  /* #15: @5 = input[4][0] */
  casadi_copy(arg[4], 6, w5);
  /* #16: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #17: @6 = (@0-@6) */
  w6  = (w0-w6);
  /* #18: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #19: @8 = 0.16 */
  w8 = 1.6000000000000003e-01;
  /* #20: @7 = (@7/@8) */
  w7 /= w8;
  /* #21: @8 = @5[1] */
  for (rr=(&w8), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #22: @8 = (@1-@8) */
  w8  = (w1-w8);
  /* #23: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #24: @10 = 0.16 */
  w10 = 1.6000000000000003e-01;
  /* #25: @9 = (@9/@10) */
  w9 /= w10;
  /* #26: @7 = (@7+@9) */
  w7 += w9;
  /* #27: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #28: @3 = (@3-@7) */
  w3 -= w7;
  /* #29: @7 = atan(@3) */
  w7 = atan( w3 );
  /* #30: @2 = (@2+@7) */
  w2 += w7;
  /* #31: @7 = 1.5708 */
  w7 = 1.5707963267948966e+00;
  /* #32: @9 = 25 */
  w9 = 25.;
  /* #33: @10 = 25 */
  w10 = 25.;
  /* #34: @11 = @5[2] */
  for (rr=(&w11), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #35: @11 = (@0-@11) */
  w11  = (w0-w11);
  /* #36: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #37: @13 = 0.16 */
  w13 = 1.6000000000000003e-01;
  /* #38: @12 = (@12/@13) */
  w12 /= w13;
  /* #39: @13 = @5[3] */
  for (rr=(&w13), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #40: @13 = (@1-@13) */
  w13  = (w1-w13);
  /* #41: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #42: @15 = 0.16 */
  w15 = 1.6000000000000003e-01;
  /* #43: @14 = (@14/@15) */
  w14 /= w15;
  /* #44: @12 = (@12+@14) */
  w12 += w14;
  /* #45: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #46: @9 = (@9-@12) */
  w9 -= w12;
  /* #47: @12 = atan(@9) */
  w12 = atan( w9 );
  /* #48: @7 = (@7+@12) */
  w7 += w12;
  /* #49: @2 = (@2+@7) */
  w2 += w7;
  /* #50: @7 = 1.5708 */
  w7 = 1.5707963267948966e+00;
  /* #51: @12 = 25 */
  w12 = 25.;
  /* #52: @14 = 25 */
  w14 = 25.;
  /* #53: @15 = @5[4] */
  for (rr=(&w15), ss=w5+4; ss!=w5+5; ss+=1) *rr++ = *ss;
  /* #54: @0 = (@0-@15) */
  w0 -= w15;
  /* #55: @15 = sq(@0) */
  w15 = casadi_sq( w0 );
  /* #56: @16 = 0.16 */
  w16 = 1.6000000000000003e-01;
  /* #57: @15 = (@15/@16) */
  w15 /= w16;
  /* #58: @16 = @5[5] */
  for (rr=(&w16), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #59: @1 = (@1-@16) */
  w1 -= w16;
  /* #60: @16 = sq(@1) */
  w16 = casadi_sq( w1 );
  /* #61: @17 = 0.16 */
  w17 = 1.6000000000000003e-01;
  /* #62: @16 = (@16/@17) */
  w16 /= w17;
  /* #63: @15 = (@15+@16) */
  w15 += w16;
  /* #64: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #65: @12 = (@12-@15) */
  w12 -= w15;
  /* #66: @15 = atan(@12) */
  w15 = atan( w12 );
  /* #67: @7 = (@7+@15) */
  w7 += w15;
  /* #68: @2 = (@2+@7) */
  w2 += w7;
  /* #69: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  /* #70: @18 = zeros(6x7,8nz) */
  casadi_clear(w18, 8);
  /* #71: @19 = ones(6x1,5nz) */
  casadi_fill(w19, 5, 1.);
  /* #72: {@2, @7, @15, NULL, @16, @17} = vertsplit(@19) */
  w2 = w19[0];
  w7 = w19[1];
  w15 = w19[2];
  w16 = w19[3];
  w17 = w19[4];
  /* #73: @20 = 00 */
  /* #74: @21 = 6.25 */
  w21 = 6.2499999999999991e+00;
  /* #75: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #76: @11 = (@11*@15) */
  w11 *= w15;
  /* #77: @21 = (@21*@11) */
  w21 *= w11;
  /* #78: @21 = (@10*@21) */
  w21  = (w10*w21);
  /* #79: @11 = 1 */
  w11 = 1.;
  /* #80: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #81: @11 = (@11+@9) */
  w11 += w9;
  /* #82: @21 = (@21/@11) */
  w21 /= w11;
  /* #83: @21 = (-@21) */
  w21 = (- w21 );
  /* #84: @9 = 6.25 */
  w9 = 6.2499999999999991e+00;
  /* #85: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #86: @6 = (@6*@15) */
  w6 *= w15;
  /* #87: @9 = (@9*@6) */
  w9 *= w6;
  /* #88: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #89: @6 = 1 */
  w6 = 1.;
  /* #90: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #91: @6 = (@6+@3) */
  w6 += w3;
  /* #92: @9 = (@9/@6) */
  w9 /= w6;
  /* #93: @21 = (@21-@9) */
  w21 -= w9;
  /* #94: @9 = 6.25 */
  w9 = 6.2499999999999991e+00;
  /* #95: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #96: @0 = (@0*@15) */
  w0 *= w15;
  /* #97: @9 = (@9*@0) */
  w9 *= w0;
  /* #98: @9 = (@14*@9) */
  w9  = (w14*w9);
  /* #99: @0 = 1 */
  w0 = 1.;
  /* #100: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #101: @0 = (@0+@12) */
  w0 += w12;
  /* #102: @9 = (@9/@0) */
  w9 /= w0;
  /* #103: @21 = (@21-@9) */
  w21 -= w9;
  /* #104: @5 = vertcat(@15, @20, @16, @17, @2, @7, @21) */
  rr=w5;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w21;
  /* #105: @22 = @5[:6] */
  for (rr=w22, ss=w5+0; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #106: (@18[0, 2, 3, 4, 5, 6] = @22) */
  for (cii=casadi_s0, rr=w18, ss=w22; cii!=casadi_s0+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #107: @20 = 00 */
  /* #108: @15 = ones(6x1,1nz) */
  w15 = 1.;
  /* #109: {NULL, NULL, NULL, @16, NULL, NULL} = vertsplit(@15) */
  w16 = w15;
  /* #110: @23 = 00 */
  /* #111: @24 = 00 */
  /* #112: @25 = 00 */
  /* #113: @26 = 00 */
  /* #114: @15 = 6.25 */
  w15 = 6.2499999999999991e+00;
  /* #115: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #116: @13 = (@13*@16) */
  w13 *= w16;
  /* #117: @15 = (@15*@13) */
  w15 *= w13;
  /* #118: @10 = (@10*@15) */
  w10 *= w15;
  /* #119: @10 = (@10/@11) */
  w10 /= w11;
  /* #120: @10 = (-@10) */
  w10 = (- w10 );
  /* #121: @11 = 6.25 */
  w11 = 6.2499999999999991e+00;
  /* #122: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #123: @8 = (@8*@16) */
  w8 *= w16;
  /* #124: @11 = (@11*@8) */
  w11 *= w8;
  /* #125: @4 = (@4*@11) */
  w4 *= w11;
  /* #126: @4 = (@4/@6) */
  w4 /= w6;
  /* #127: @10 = (@10-@4) */
  w10 -= w4;
  /* #128: @4 = 6.25 */
  w4 = 6.2499999999999991e+00;
  /* #129: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #130: @1 = (@1*@16) */
  w1 *= w16;
  /* #131: @4 = (@4*@1) */
  w4 *= w1;
  /* #132: @14 = (@14*@4) */
  w14 *= w4;
  /* #133: @14 = (@14/@0) */
  w14 /= w0;
  /* #134: @10 = (@10-@14) */
  w10 -= w14;
  /* #135: @27 = vertcat(@20, @16, @23, @24, @25, @26, @10) */
  rr=w27;
  *rr++ = w16;
  *rr++ = w10;
  /* #136: @28 = @27[:2] */
  for (rr=w28, ss=w27+0; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #137: (@18[1:13:6] = @28) */
  for (rr=w18+1, ss=w28; rr!=w18+13; rr+=6) *rr = *ss++;
  /* #138: output[1][0] = @18 */
  casadi_copy(w18, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mobile_robot_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 47;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
