/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mobile_robot_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {4, 4, 0, 2, 4, 4, 4, 0, 1, 0, 1};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};

/* mobile_robot_cost_y_e_hess:(i0[4],i1[],i2[],i3[5],i4[],i5[2x3])->(o0[4x4,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, *w3=w+6, w4, w5, w6, w7, *w8=w+15, w9, w10, w11, w12, w13, w14, *w15=w+27, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, *w36=w+48, *w37=w+50, *w38=w+52;
  /* #0: @0 = zeros(4x4,4nz) */
  casadi_clear(w0, 4);
  /* #1: @1 = 6.25 */
  w1 = 6.2499999999999991e+00;
  /* #2: @2 = 25 */
  w2 = 25.;
  /* #3: @3 = input[3][0] */
  casadi_copy(arg[3], 5, w3);
  /* #4: {NULL, NULL, NULL, NULL, @4} = vertsplit(@3) */
  w4 = w3[4];
  /* #5: @5 = 1 */
  w5 = 1.;
  /* #6: @6 = 25 */
  w6 = 25.;
  /* #7: @7 = input[0][0] */
  w7 = arg[0] ? arg[0][0] : 0;
  /* #8: @8 = input[5][0] */
  casadi_copy(arg[5], 6, w8);
  /* #9: @9 = @8[4] */
  for (rr=(&w9), ss=w8+4; ss!=w8+5; ss+=1) *rr++ = *ss;
  /* #10: @9 = (@7-@9) */
  w9  = (w7-w9);
  /* #11: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #12: @11 = 0.16 */
  w11 = 1.6000000000000003e-01;
  /* #13: @10 = (@10/@11) */
  w10 /= w11;
  /* #14: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #15: @12 = @8[5] */
  for (rr=(&w12), ss=w8+5; ss!=w8+6; ss+=1) *rr++ = *ss;
  /* #16: @12 = (@11-@12) */
  w12  = (w11-w12);
  /* #17: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #18: @14 = 0.16 */
  w14 = 1.6000000000000003e-01;
  /* #19: @13 = (@13/@14) */
  w13 /= w14;
  /* #20: @10 = (@10+@13) */
  w10 += w13;
  /* #21: @10 = (@2*@10) */
  w10  = (w2*w10);
  /* #22: @6 = (@6-@10) */
  w6 -= w10;
  /* #23: @10 = sq(@6) */
  w10 = casadi_sq( w6 );
  /* #24: @5 = (@5+@10) */
  w5 += w10;
  /* #25: @10 = (@4/@5) */
  w10  = (w4/w5);
  /* #26: @13 = (@2*@10) */
  w13  = (w2*w10);
  /* #27: @14 = (@1*@13) */
  w14  = (w1*w13);
  /* #28: @15 = ones(4x1,3nz) */
  casadi_fill(w15, 3, 1.);
  /* #29: {@16, NULL, NULL, NULL} = vertsplit(@15) */
  w16 = w15[0];
  /* #30: @17 = (2.*@16) */
  w17 = (2.* w16 );
  /* #31: @14 = (@14*@17) */
  w14 *= w17;
  /* #32: @17 = (2.*@9) */
  w17 = (2.* w9 );
  /* #33: @10 = (@10/@5) */
  w10 /= w5;
  /* #34: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #35: @5 = 6.25 */
  w5 = 6.2499999999999991e+00;
  /* #36: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #37: @9 = (@9*@16) */
  w9 *= w16;
  /* #38: @5 = (@5*@9) */
  w5 *= w9;
  /* #39: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #40: @5 = (@6*@5) */
  w5  = (w6*w5);
  /* #41: @5 = (@10*@5) */
  w5  = (w10*w5);
  /* #42: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #43: @9 = (@1*@5) */
  w9  = (w1*w5);
  /* #44: @9 = (@17*@9) */
  w9  = (w17*w9);
  /* #45: @14 = (@14+@9) */
  w14 += w9;
  /* #46: @14 = (-@14) */
  w14 = (- w14 );
  /* #47: @9 = 6.25 */
  w9 = 6.2499999999999991e+00;
  /* #48: @18 = 25 */
  w18 = 25.;
  /* #49: @19 = 1 */
  w19 = 1.;
  /* #50: @20 = 25 */
  w20 = 25.;
  /* #51: @21 = @8[2] */
  for (rr=(&w21), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #52: @21 = (@7-@21) */
  w21  = (w7-w21);
  /* #53: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #54: @23 = 0.16 */
  w23 = 1.6000000000000003e-01;
  /* #55: @22 = (@22/@23) */
  w22 /= w23;
  /* #56: @23 = @8[3] */
  for (rr=(&w23), ss=w8+3; ss!=w8+4; ss+=1) *rr++ = *ss;
  /* #57: @23 = (@11-@23) */
  w23  = (w11-w23);
  /* #58: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #59: @25 = 0.16 */
  w25 = 1.6000000000000003e-01;
  /* #60: @24 = (@24/@25) */
  w24 /= w25;
  /* #61: @22 = (@22+@24) */
  w22 += w24;
  /* #62: @22 = (@18*@22) */
  w22  = (w18*w22);
  /* #63: @20 = (@20-@22) */
  w20 -= w22;
  /* #64: @22 = sq(@20) */
  w22 = casadi_sq( w20 );
  /* #65: @19 = (@19+@22) */
  w19 += w22;
  /* #66: @22 = (@4/@19) */
  w22  = (w4/w19);
  /* #67: @24 = (@18*@22) */
  w24  = (w18*w22);
  /* #68: @25 = (@9*@24) */
  w25  = (w9*w24);
  /* #69: @26 = (2.*@16) */
  w26 = (2.* w16 );
  /* #70: @25 = (@25*@26) */
  w25 *= w26;
  /* #71: @26 = (2.*@21) */
  w26 = (2.* w21 );
  /* #72: @22 = (@22/@19) */
  w22 /= w19;
  /* #73: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #74: @19 = 6.25 */
  w19 = 6.2499999999999991e+00;
  /* #75: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #76: @21 = (@21*@16) */
  w21 *= w16;
  /* #77: @19 = (@19*@21) */
  w19 *= w21;
  /* #78: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #79: @19 = (@20*@19) */
  w19  = (w20*w19);
  /* #80: @19 = (@22*@19) */
  w19  = (w22*w19);
  /* #81: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #82: @21 = (@9*@19) */
  w21  = (w9*w19);
  /* #83: @21 = (@26*@21) */
  w21  = (w26*w21);
  /* #84: @25 = (@25+@21) */
  w25 += w21;
  /* #85: @14 = (@14-@25) */
  w14 -= w25;
  /* #86: @25 = 6.25 */
  w25 = 6.2499999999999991e+00;
  /* #87: @21 = 25 */
  w21 = 25.;
  /* #88: @27 = 1 */
  w27 = 1.;
  /* #89: @28 = 25 */
  w28 = 25.;
  /* #90: @29 = @8[0] */
  for (rr=(&w29), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #91: @7 = (@7-@29) */
  w7 -= w29;
  /* #92: @29 = sq(@7) */
  w29 = casadi_sq( w7 );
  /* #93: @30 = 0.16 */
  w30 = 1.6000000000000003e-01;
  /* #94: @29 = (@29/@30) */
  w29 /= w30;
  /* #95: @30 = @8[1] */
  for (rr=(&w30), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #96: @11 = (@11-@30) */
  w11 -= w30;
  /* #97: @30 = sq(@11) */
  w30 = casadi_sq( w11 );
  /* #98: @31 = 0.16 */
  w31 = 1.6000000000000003e-01;
  /* #99: @30 = (@30/@31) */
  w30 /= w31;
  /* #100: @29 = (@29+@30) */
  w29 += w30;
  /* #101: @29 = (@21*@29) */
  w29  = (w21*w29);
  /* #102: @28 = (@28-@29) */
  w28 -= w29;
  /* #103: @29 = sq(@28) */
  w29 = casadi_sq( w28 );
  /* #104: @27 = (@27+@29) */
  w27 += w29;
  /* #105: @4 = (@4/@27) */
  w4 /= w27;
  /* #106: @29 = (@21*@4) */
  w29  = (w21*w4);
  /* #107: @30 = (@25*@29) */
  w30  = (w25*w29);
  /* #108: @31 = (2.*@16) */
  w31 = (2.* w16 );
  /* #109: @30 = (@30*@31) */
  w30 *= w31;
  /* #110: @31 = (2.*@7) */
  w31 = (2.* w7 );
  /* #111: @4 = (@4/@27) */
  w4 /= w27;
  /* #112: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #113: @27 = 6.25 */
  w27 = 6.2499999999999991e+00;
  /* #114: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #115: @7 = (@7*@16) */
  w7 *= w16;
  /* #116: @27 = (@27*@7) */
  w27 *= w7;
  /* #117: @27 = (@21*@27) */
  w27  = (w21*w27);
  /* #118: @27 = (@28*@27) */
  w27  = (w28*w27);
  /* #119: @27 = (@4*@27) */
  w27  = (w4*w27);
  /* #120: @27 = (@21*@27) */
  w27  = (w21*w27);
  /* #121: @7 = (@25*@27) */
  w7  = (w25*w27);
  /* #122: @7 = (@31*@7) */
  w7  = (w31*w7);
  /* #123: @30 = (@30+@7) */
  w30 += w7;
  /* #124: @14 = (@14-@30) */
  w14 -= w30;
  /* #125: @30 = (2.*@12) */
  w30 = (2.* w12 );
  /* #126: @7 = 6.25 */
  w7 = 6.2499999999999991e+00;
  /* #127: @5 = (@7*@5) */
  w5  = (w7*w5);
  /* #128: @5 = (@30*@5) */
  w5  = (w30*w5);
  /* #129: @5 = (-@5) */
  w5 = (- w5 );
  /* #130: @16 = (2.*@23) */
  w16 = (2.* w23 );
  /* #131: @32 = 6.25 */
  w32 = 6.2499999999999991e+00;
  /* #132: @19 = (@32*@19) */
  w19  = (w32*w19);
  /* #133: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #134: @5 = (@5-@19) */
  w5 -= w19;
  /* #135: @19 = (2.*@11) */
  w19 = (2.* w11 );
  /* #136: @33 = 6.25 */
  w33 = 6.2499999999999991e+00;
  /* #137: @27 = (@33*@27) */
  w27  = (w33*w27);
  /* #138: @27 = (@19*@27) */
  w27  = (w19*w27);
  /* #139: @5 = (@5-@27) */
  w5 -= w27;
  /* #140: @34 = 00 */
  /* #141: @35 = 00 */
  /* #142: @36 = vertcat(@14, @5, @34, @35) */
  rr=w36;
  *rr++ = w14;
  *rr++ = w5;
  /* #143: @37 = @36[:2] */
  for (rr=w37, ss=w36+0; ss!=w36+2; ss+=1) *rr++ = *ss;
  /* #144: (@0[:4:2] = @37) */
  for (rr=w0+0, ss=w37; rr!=w0+4; rr+=2) *rr = *ss++;
  /* #145: @14 = 6.25 */
  w14 = 6.2499999999999991e+00;
  /* #146: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #147: @5 = ones(4x1,1nz) */
  w5 = 1.;
  /* #148: {NULL, @27, NULL, NULL} = vertsplit(@5) */
  w27 = w5;
  /* #149: @12 = (@12*@27) */
  w12 *= w27;
  /* #150: @14 = (@14*@12) */
  w14 *= w12;
  /* #151: @14 = (@2*@14) */
  w14  = (w2*w14);
  /* #152: @6 = (@6*@14) */
  w6 *= w14;
  /* #153: @10 = (@10*@6) */
  w10 *= w6;
  /* #154: @2 = (@2*@10) */
  w2 *= w10;
  /* #155: @1 = (@1*@2) */
  w1 *= w2;
  /* #156: @17 = (@17*@1) */
  w17 *= w1;
  /* #157: @17 = (-@17) */
  w17 = (- w17 );
  /* #158: @1 = 6.25 */
  w1 = 6.2499999999999991e+00;
  /* #159: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #160: @23 = (@23*@27) */
  w23 *= w27;
  /* #161: @1 = (@1*@23) */
  w1 *= w23;
  /* #162: @1 = (@18*@1) */
  w1  = (w18*w1);
  /* #163: @20 = (@20*@1) */
  w20 *= w1;
  /* #164: @22 = (@22*@20) */
  w22 *= w20;
  /* #165: @18 = (@18*@22) */
  w18 *= w22;
  /* #166: @9 = (@9*@18) */
  w9 *= w18;
  /* #167: @26 = (@26*@9) */
  w26 *= w9;
  /* #168: @17 = (@17-@26) */
  w17 -= w26;
  /* #169: @26 = 6.25 */
  w26 = 6.2499999999999991e+00;
  /* #170: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #171: @11 = (@11*@27) */
  w11 *= w27;
  /* #172: @26 = (@26*@11) */
  w26 *= w11;
  /* #173: @26 = (@21*@26) */
  w26  = (w21*w26);
  /* #174: @28 = (@28*@26) */
  w28 *= w26;
  /* #175: @4 = (@4*@28) */
  w4 *= w28;
  /* #176: @21 = (@21*@4) */
  w21 *= w4;
  /* #177: @25 = (@25*@21) */
  w25 *= w21;
  /* #178: @31 = (@31*@25) */
  w31 *= w25;
  /* #179: @17 = (@17-@31) */
  w17 -= w31;
  /* #180: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #181: @31 = (2.*@27) */
  w31 = (2.* w27 );
  /* #182: @13 = (@13*@31) */
  w13 *= w31;
  /* #183: @7 = (@7*@2) */
  w7 *= w2;
  /* #184: @30 = (@30*@7) */
  w30 *= w7;
  /* #185: @13 = (@13+@30) */
  w13 += w30;
  /* #186: @13 = (-@13) */
  w13 = (- w13 );
  /* #187: @24 = (@32*@24) */
  w24  = (w32*w24);
  /* #188: @30 = (2.*@27) */
  w30 = (2.* w27 );
  /* #189: @24 = (@24*@30) */
  w24 *= w30;
  /* #190: @32 = (@32*@18) */
  w32 *= w18;
  /* #191: @16 = (@16*@32) */
  w16 *= w32;
  /* #192: @24 = (@24+@16) */
  w24 += w16;
  /* #193: @13 = (@13-@24) */
  w13 -= w24;
  /* #194: @29 = (@33*@29) */
  w29  = (w33*w29);
  /* #195: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #196: @29 = (@29*@27) */
  w29 *= w27;
  /* #197: @33 = (@33*@21) */
  w33 *= w21;
  /* #198: @19 = (@19*@33) */
  w19 *= w33;
  /* #199: @29 = (@29+@19) */
  w29 += w19;
  /* #200: @13 = (@13-@29) */
  w13 -= w29;
  /* #201: @34 = 00 */
  /* #202: @35 = 00 */
  /* #203: @37 = vertcat(@17, @13, @34, @35) */
  rr=w37;
  *rr++ = w17;
  *rr++ = w13;
  /* #204: @36 = @37[:2] */
  for (rr=w36, ss=w37+0; ss!=w37+2; ss+=1) *rr++ = *ss;
  /* #205: (@0[1:5:2] = @36) */
  for (rr=w0+1, ss=w36; rr!=w0+5; rr+=2) *rr = *ss++;
  /* #206: @38 = @0' */
  casadi_trans(w0,casadi_s0, w38, casadi_s0, iw);
  /* #207: output[0][0] = @38 */
  casadi_copy(w38, 4, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mobile_robot_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 56;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
