/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mobile_robot_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[4] = {0, 2, 3, 4};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[12] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[14] = {4, 5, 0, 1, 2, 3, 4, 6, 0, 1, 2, 3, 0, 1};
static const casadi_int casadi_s6[3] = {5, 0, 0};

/* mobile_robot_cost_y_e_fun_jac_ut_xt:(i0[4],i1[],i2[],i3[],i4[2x3])->(o0[5],o1[4x5,6nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  const casadi_int *cii;
  casadi_real w0, w1, w2, w3, w4, *w5=w+5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+23, *w20=w+26, *w21=w+30, *w24=w+34, *w25=w+36;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #4: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #6: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #8: @2 = 1.5708 */
  w2 = 1.5707963267948966e+00;
  /* #9: @3 = 25 */
  w3 = 25.;
  /* #10: @4 = 25 */
  w4 = 25.;
  /* #11: @5 = input[4][0] */
  casadi_copy(arg[4], 6, w5);
  /* #12: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #13: @6 = (@0-@6) */
  w6  = (w0-w6);
  /* #14: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #15: @8 = 0.16 */
  w8 = 1.6000000000000003e-01;
  /* #16: @7 = (@7/@8) */
  w7 /= w8;
  /* #17: @8 = @5[1] */
  for (rr=(&w8), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #18: @8 = (@1-@8) */
  w8  = (w1-w8);
  /* #19: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #20: @10 = 0.16 */
  w10 = 1.6000000000000003e-01;
  /* #21: @9 = (@9/@10) */
  w9 /= w10;
  /* #22: @7 = (@7+@9) */
  w7 += w9;
  /* #23: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #24: @3 = (@3-@7) */
  w3 -= w7;
  /* #25: @7 = atan(@3) */
  w7 = atan( w3 );
  /* #26: @2 = (@2+@7) */
  w2 += w7;
  /* #27: @7 = 1.5708 */
  w7 = 1.5707963267948966e+00;
  /* #28: @9 = 25 */
  w9 = 25.;
  /* #29: @10 = 25 */
  w10 = 25.;
  /* #30: @11 = @5[2] */
  for (rr=(&w11), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #31: @11 = (@0-@11) */
  w11  = (w0-w11);
  /* #32: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #33: @13 = 0.16 */
  w13 = 1.6000000000000003e-01;
  /* #34: @12 = (@12/@13) */
  w12 /= w13;
  /* #35: @13 = @5[3] */
  for (rr=(&w13), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #36: @13 = (@1-@13) */
  w13  = (w1-w13);
  /* #37: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #38: @15 = 0.16 */
  w15 = 1.6000000000000003e-01;
  /* #39: @14 = (@14/@15) */
  w14 /= w15;
  /* #40: @12 = (@12+@14) */
  w12 += w14;
  /* #41: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #42: @9 = (@9-@12) */
  w9 -= w12;
  /* #43: @12 = atan(@9) */
  w12 = atan( w9 );
  /* #44: @7 = (@7+@12) */
  w7 += w12;
  /* #45: @2 = (@2+@7) */
  w2 += w7;
  /* #46: @7 = 1.5708 */
  w7 = 1.5707963267948966e+00;
  /* #47: @12 = 25 */
  w12 = 25.;
  /* #48: @14 = 25 */
  w14 = 25.;
  /* #49: @15 = @5[4] */
  for (rr=(&w15), ss=w5+4; ss!=w5+5; ss+=1) *rr++ = *ss;
  /* #50: @0 = (@0-@15) */
  w0 -= w15;
  /* #51: @15 = sq(@0) */
  w15 = casadi_sq( w0 );
  /* #52: @16 = 0.16 */
  w16 = 1.6000000000000003e-01;
  /* #53: @15 = (@15/@16) */
  w15 /= w16;
  /* #54: @16 = @5[5] */
  for (rr=(&w16), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #55: @1 = (@1-@16) */
  w1 -= w16;
  /* #56: @16 = sq(@1) */
  w16 = casadi_sq( w1 );
  /* #57: @17 = 0.16 */
  w17 = 1.6000000000000003e-01;
  /* #58: @16 = (@16/@17) */
  w16 /= w17;
  /* #59: @15 = (@15+@16) */
  w15 += w16;
  /* #60: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #61: @12 = (@12-@15) */
  w12 -= w15;
  /* #62: @15 = atan(@12) */
  w15 = atan( w12 );
  /* #63: @7 = (@7+@15) */
  w7 += w15;
  /* #64: @2 = (@2+@7) */
  w2 += w7;
  /* #65: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #66: @5 = zeros(4x5,6nz) */
  casadi_clear(w5, 6);
  /* #67: @18 = ones(4x1,3nz) */
  casadi_fill(w18, 3, 1.);
  /* #68: {@2, NULL, @7, @15} = vertsplit(@18) */
  w2 = w18[0];
  w7 = w18[1];
  w15 = w18[2];
  /* #69: @19 = 00 */
  /* #70: @16 = 6.25 */
  w16 = 6.2499999999999991e+00;
  /* #71: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #72: @11 = (@11*@2) */
  w11 *= w2;
  /* #73: @16 = (@16*@11) */
  w16 *= w11;
  /* #74: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #75: @11 = 1 */
  w11 = 1.;
  /* #76: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #77: @11 = (@11+@9) */
  w11 += w9;
  /* #78: @16 = (@16/@11) */
  w16 /= w11;
  /* #79: @16 = (-@16) */
  w16 = (- w16 );
  /* #80: @9 = 6.25 */
  w9 = 6.2499999999999991e+00;
  /* #81: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #82: @6 = (@6*@2) */
  w6 *= w2;
  /* #83: @9 = (@9*@6) */
  w9 *= w6;
  /* #84: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #85: @6 = 1 */
  w6 = 1.;
  /* #86: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #87: @6 = (@6+@3) */
  w6 += w3;
  /* #88: @9 = (@9/@6) */
  w9 /= w6;
  /* #89: @16 = (@16-@9) */
  w16 -= w9;
  /* #90: @9 = 6.25 */
  w9 = 6.2499999999999991e+00;
  /* #91: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #92: @0 = (@0*@2) */
  w0 *= w2;
  /* #93: @9 = (@9*@0) */
  w9 *= w0;
  /* #94: @9 = (@14*@9) */
  w9  = (w14*w9);
  /* #95: @0 = 1 */
  w0 = 1.;
  /* #96: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #97: @0 = (@0+@12) */
  w0 += w12;
  /* #98: @9 = (@9/@0) */
  w9 /= w0;
  /* #99: @16 = (@16-@9) */
  w16 -= w9;
  /* #100: @20 = vertcat(@2, @19, @7, @15, @16) */
  rr=w20;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w15;
  *rr++ = w16;
  /* #101: @21 = @20[:4] */
  for (rr=w21, ss=w20+0; ss!=w20+4; ss+=1) *rr++ = *ss;
  /* #102: (@5[0, 2, 3, 4] = @21) */
  for (cii=casadi_s0, rr=w5, ss=w21; cii!=casadi_s0+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #103: @19 = 00 */
  /* #104: @2 = ones(4x1,1nz) */
  w2 = 1.;
  /* #105: {NULL, @7, NULL, NULL} = vertsplit(@2) */
  w7 = w2;
  /* #106: @22 = 00 */
  /* #107: @23 = 00 */
  /* #108: @2 = 6.25 */
  w2 = 6.2499999999999991e+00;
  /* #109: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #110: @13 = (@13*@7) */
  w13 *= w7;
  /* #111: @2 = (@2*@13) */
  w2 *= w13;
  /* #112: @10 = (@10*@2) */
  w10 *= w2;
  /* #113: @10 = (@10/@11) */
  w10 /= w11;
  /* #114: @10 = (-@10) */
  w10 = (- w10 );
  /* #115: @11 = 6.25 */
  w11 = 6.2499999999999991e+00;
  /* #116: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #117: @8 = (@8*@7) */
  w8 *= w7;
  /* #118: @11 = (@11*@8) */
  w11 *= w8;
  /* #119: @4 = (@4*@11) */
  w4 *= w11;
  /* #120: @4 = (@4/@6) */
  w4 /= w6;
  /* #121: @10 = (@10-@4) */
  w10 -= w4;
  /* #122: @4 = 6.25 */
  w4 = 6.2499999999999991e+00;
  /* #123: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #124: @1 = (@1*@7) */
  w1 *= w7;
  /* #125: @4 = (@4*@1) */
  w4 *= w1;
  /* #126: @14 = (@14*@4) */
  w14 *= w4;
  /* #127: @14 = (@14/@0) */
  w14 /= w0;
  /* #128: @10 = (@10-@14) */
  w10 -= w14;
  /* #129: @24 = vertcat(@19, @7, @22, @23, @10) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w10;
  /* #130: @25 = @24[:2] */
  for (rr=w25, ss=w24+0; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #131: (@5[1:9:4] = @25) */
  for (rr=w5+1, ss=w25; rr!=w5+9; rr+=4) *rr = *ss++;
  /* #132: output[1][0] = @5 */
  casadi_copy(w5, 6, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void mobile_robot_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mobile_robot_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mobile_robot_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_robot_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_robot_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mobile_robot_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 38;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
